
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ap952080
 */
public class AjoutLieuDlg extends javax.swing.JDialog {

    /**
     * Creates new form AjoutLieuDlg1
     */
   
    private Personnage ljdiag[];
    private LesLieux ll;
    private Lieu nouveauLieu;
    private Image img;
    private Personnage occ;
    private String path;
    
    
    public AjoutLieuDlg(java.awt.Frame parent, boolean modal, Personnage lj[], LesLieux lesL) {
        super(parent, modal);
        initComponents();
        ljdiag = lj;
        ll = lesL;  
        information.setText(" INFORMATION : \n Veuillez choisir dans la liste le Personnage Non Joueur que \n vous souhaitez avoir dans ce lieu puis \n veuillez saisir le type du lieu ex : Salle Mystère ... \n puis la description du lieu ex : Salle de la mort ... \n enfin l'image du lieu est à renseigner en cliquant \n sur le bouton Image une fenêtre apparaîtra qui \n vous permetttra de sélectionner une image \n cherchez donc une photo que vous avez sur votre ordinateur. \n Je vous souhaites une bonne partie !  ");
        initComboPNJ();
        nouveauLieu = null;
        this.setSize(800,700);
        this.setTitle("Ajout Lieu");
        this.setVisible(true);
        this.setLocation(600,200); 
    }
    
     /*public void paint(Graphics g) 
    { 
    super.paint(g);
    if(img != null)
        {
            Graphics gg= Photo.getGraphics(); 
            gg.drawImage(img, 0, 0, Photo.getWidth(), Photo.getHeight(), this); 
        } 
    }*/
    
    public void initComboPNJ(){
        occupantCombo.removeAllItems();
        occupantCombo.addItem("Choisir un PNJ !");
        for(int i=0;i<ll.getNbl();i++)
         { 
          occupantCombo.addItem(ll.getLieu(i).getOccupant().getNom());   
         }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        occupantCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        information = new javax.swing.JTextArea();
        open = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        typeLieu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        descLieu = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        AnnulerChoixPerso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Création d'un lieu :");
        jPanel1.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel5.setLayout(new java.awt.GridLayout(1, 1));

        jPanel3.setLayout(new java.awt.GridLayout(3, 1));

        occupantCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir un PNJ" }));
        occupantCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupantComboActionPerformed(evt);
            }
        });
        jPanel3.add(occupantCombo);

        information.setColumns(20);
        information.setRows(5);
        jScrollPane1.setViewportView(information);

        jPanel3.add(jScrollPane1);

        open.setText("Image");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        jPanel3.add(open);

        jPanel5.add(jPanel3);

        jPanel2.add(jPanel5);

        jPanel8.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("Type du Lieu :");
        jPanel8.add(jLabel1);
        jPanel8.add(typeLieu);

        jLabel2.setText("Description du Lieu :");
        jPanel8.add(jLabel2);
        jPanel8.add(descLieu);

        jPanel2.add(jPanel8);

        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        AnnulerChoixPerso.setText("Annuler");
        AnnulerChoixPerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerChoixPersoActionPerformed(evt);
            }
        });
        jPanel4.add(AnnulerChoixPerso);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void occupantComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupantComboActionPerformed

    }//GEN-LAST:event_occupantComboActionPerformed

    private void AnnulerChoixPersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerChoixPersoActionPerformed
        this.dispose();
    }//GEN-LAST:event_AnnulerChoixPersoActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.setVisible(true);
        
        if ( jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)
        { 
        path = jf.getSelectedFile().getPath();
        String typeL = typeLieu.getText();
        String descL =  descLieu.getText();
        occ = ll.getLieu(occupantCombo.getSelectedIndex()-1).getOccupant(); //NULLPOINTER
        nouveauLieu = new Lieu(typeL, descL, occ);      
        img = Toolkit.getDefaultToolkit().getImage(path);
        nouveauLieu.setPhoto(img);
        ll.ajoutLieu(nouveauLieu);
        this.dispose();
        }
    }//GEN-LAST:event_openActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutLieuDlg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutLieuDlg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutLieuDlg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutLieuDlg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjoutLieuDlg1 dialog = new AjoutLieuDlg1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnulerChoixPerso;
    private javax.swing.JTextField descLieu;
    private javax.swing.JTextArea information;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> occupantCombo;
    private javax.swing.JButton open;
    private javax.swing.JTextField typeLieu;
    // End of variables declaration//GEN-END:variables
}
