
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.DefaultListModel;
import javax.swing.Icon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*
*TODO*

CORRIGER COMBATPOTION
Optimisation???
sinon c finit

*ENDTODO*
*/

/**
 *
 * @author ap952080
 */
public class ApprendreDlg extends javax.swing.JDialog {

    /**
     * Creates new form ApprendreDlg
     */
    
    private Apprentissage act;
    private boolean ok;
    private Lieu lieu;
    private Personnage pc;
    private Image img;
    private Sort js;
    
    public ApprendreDlg(java.awt.Frame parent, boolean modal, Personnage p, Lieu l1) {
        super(parent, modal);
        initComponents(); 
        // création de la JDialog
        initPanneau(img); 
        // creation du Panneau pour les imgs
        pc=p; 
        // on fixe le personnage qui arrive dans ce lieu à p
        lieu=l1; 
        // on fixe le lieu de l'activite a l1
        sortPNJ.setText(lieu.getOccupant().getArmes().toString());
        // on affiche les sorts du PNJ
        img=lieu.getOccupant().getPhoto();
        repaint();
        // on affiche la photo du PNJ grace a repaint()
        nomPNJ.setText(lieu.getOccupant().getNom());
        // on affiche le nom du PNJ
        initSorts();
        // creation de la liste des sorts a apprendre
        this.setSize(530,450);
        this.setTitle("Apprendre");
        this.setVisible(true);
        this.setLocation(600,200);
        // on fixe la taille, le titre, la position de la fenetre
    }
    
    public void paint(Graphics g) 
    { 
    super.paint(g);
    if(img != null)
        {
            Graphics gg= Panneau.getGraphics(); 
            gg.drawImage(img, 0, 0, Panneau.getWidth(), Panneau.getHeight(), this); 
        } 
    }
    
    private void initPanneau(Image img){
    //creation du panneau
    PanneauImage pi = new PanneauImage(img);
    Panneau.add(pi);
    Panneau.setLayout(new GridLayout(1,1)); 
    }
    
    
    private void initSorts(){
       DefaultListModel lst = new DefaultListModel();
       for(int i=0;i<lieu.getOccupant().getArmes().getSorts().getNbArme();i++)
       {
            lst.addElement(lieu.getOccupant().getArmes().getSorts().getArme(i));
       }
       sortApprendre.setModel(lst); 
    }
    
    
    
    public boolean cOk() {
        return ok;  
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomPNJ = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Panneau = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sortPNJ = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        info = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        sortApprendre = new javax.swing.JList<>();
        Apprendre = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultat = new javax.swing.JTextArea();
        Fermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nomPNJ.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(nomPNJ);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));
        jPanel2.add(Panneau);

        sortPNJ.setColumns(20);
        sortPNJ.setRows(5);
        sortPNJ.setText("\n");
        jScrollPane2.setViewportView(sortPNJ);

        jPanel2.add(jScrollPane2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(6, 1));

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));
        jPanel4.add(info);

        jPanel3.add(jPanel4);

        jLabel2.setText("Sort à apprendre :");
        jPanel3.add(jLabel2);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setViewportView(sortApprendre);

        jPanel5.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5);

        Apprendre.setText("Apprendre");
        Apprendre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApprendreActionPerformed(evt);
            }
        });
        jPanel3.add(Apprendre);

        Resultat.setColumns(20);
        Resultat.setRows(5);
        jScrollPane1.setViewportView(Resultat);

        jPanel3.add(jScrollPane1);

        Fermer.setText("Fermer");
        Fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FermerActionPerformed(evt);
            }
        });
        jPanel3.add(Fermer);

        getContentPane().add(jPanel3, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ApprendreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApprendreActionPerformed
     
        
        if(sortApprendre.getSelectedIndex() != -1)
           {
            for(Arme ar : lieu.getOccupant().getArmes().getLstArmes()) //parcoure les armes             
            {   
                if(ar.getNom().equals(lieu.getOccupant().getArmes().getArme(sortApprendre.getSelectedIndex()).getNom())) // si nom sort = nom du sort sélectionnné à l'index de la jlist                                    
                js = new Sort(ar.getNom(), ar.getForce());   
            }
            act = new Apprentissage(js, pc, lieu);
            act.execute();
            ok = true;
            Resultat.setText(act.getDescriptif());
            Apprendre.setEnabled(false);
            
           }
           else
           {
               info.setText("Choisissez un sort !");
           }
    }//GEN-LAST:event_ApprendreActionPerformed

    private void FermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FermerActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_FermerActionPerformed

    /**
     * @param args the command line arguments
     */
    
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApprendreDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApprendreDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApprendreDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApprendreDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold> */

        /* Create and display the dialog */
       /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ApprendreDlg dialog = new ApprendreDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apprendre;
    private javax.swing.JButton Fermer;
    private javax.swing.JPanel Panneau;
    private javax.swing.JTextArea Resultat;
    private javax.swing.JLabel info;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nomPNJ;
    private javax.swing.JList<String> sortApprendre;
    private javax.swing.JTextArea sortPNJ;
    // End of variables declaration//GEN-END:variables
}
