
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.DefaultListModel;
import javax.swing.JRadioButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ap952080
 */
public class ChoixDlg extends javax.swing.JDialog {

    /**
     * Creates new form ChoixDlg2
     */
    
    private boolean ok = false;
    private Personnage ljdiag[];
    private Personnage pc = null;
    private Image img;
    private Image inconnu = Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images/inconnu.png"));
 
    
    public ChoixDlg(java.awt.Frame parent, boolean modal, Personnage lj[]) {
        super(parent, modal);
        initComponents();
        img=inconnu;
        repaint();
        ljdiag = lj; 
        initCBPersonnage();
        this.setSize(800,700);
        this.setTitle("Choix");
        this.setVisible(true);
        this.setLocation(600,200);  
    }
    


    public Personnage getJoueur(){
        
       return ljdiag[CBPersonnage.getSelectedIndex()];
    }

    
    
    // initialisation de la comboBox Personnage
    public void initCBPersonnage()
    {
       CBPersonnage.removeAllItems();
       int nbperso = ljdiag.length;
       for (int i=0;i<nbperso;i++)
       CBPersonnage.addItem(ljdiag[i].getNom());      
    }

    
    
    public void paint(Graphics g) 
    { 
    super.paint(g);
    if(img != null)
        {
            Graphics gg= Photo.getGraphics(); 
            gg.drawImage(img, 0, 0, Photo.getWidth(), Photo.getHeight(), this); 
        } 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CBPersonnage = new javax.swing.JComboBox<>();
        lesSorts = new javax.swing.JLabel();
        Sort1 = new javax.swing.JRadioButton();
        Sort2 = new javax.swing.JRadioButton();
        Sort3 = new javax.swing.JRadioButton();
        Sort4 = new javax.swing.JRadioButton();
        Sort5 = new javax.swing.JRadioButton();
        Sort6 = new javax.swing.JRadioButton();
        Panneau = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LPotions = new javax.swing.JList<>();
        Photo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        AnnulerChoixPerso = new javax.swing.JButton();
        ValiderPerso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Choix du Personnage");
        jPanel1.add(jLabel4);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel5.setLayout(new java.awt.GridLayout(10, 1));

        jLabel5.setText("Choisir le personnage que vous souhaitez incarner dans la liste");
        jPanel5.add(jLabel5);

        CBPersonnage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Remplissage Automatique" }));
        CBPersonnage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPersonnageActionPerformed(evt);
            }
        });
        jPanel5.add(CBPersonnage);

        lesSorts.setText("Sorts en possession du Personnage");
        jPanel5.add(lesSorts);

        Sort1.setText("Expelliarmus");
        jPanel5.add(Sort1);

        Sort2.setText("Stupefix");
        jPanel5.add(Sort2);

        Sort3.setText("Reducto");
        jPanel5.add(Sort3);

        Sort4.setText("Avada Kedavra");
        jPanel5.add(Sort4);

        Sort5.setText("Endoloris");
        jPanel5.add(Sort5);

        Sort6.setText("Impero");
        jPanel5.add(Sort6);

        jPanel2.add(jPanel5);

        Panneau.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Listes des Potions du Personnage");
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 15));
        Panneau.add(jLabel1, java.awt.BorderLayout.CENTER);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(274, 200));

        LPotions.setPreferredSize(new java.awt.Dimension(400, 400));
        jScrollPane2.setViewportView(LPotions);

        Panneau.add(jScrollPane2, java.awt.BorderLayout.PAGE_END);

        Photo.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout PhotoLayout = new javax.swing.GroupLayout(Photo);
        Photo.setLayout(PhotoLayout);
        PhotoLayout.setHorizontalGroup(
            PhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        PhotoLayout.setVerticalGroup(
            PhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        Panneau.add(Photo, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(Panneau);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        AnnulerChoixPerso.setText("Annuler");
        AnnulerChoixPerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerChoixPersoActionPerformed(evt);
            }
        });
        jPanel4.add(AnnulerChoixPerso);

        ValiderPerso.setText("Valider");
        ValiderPerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderPersoActionPerformed(evt);
            }
        });
        jPanel4.add(ValiderPerso);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBPersonnageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPersonnageActionPerformed
       int numperso = CBPersonnage.getSelectedIndex();
       
        Image img1 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images/harrypotter.jpg"));
        Image img2 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images/hermione.jpg"));
        Image img3 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images/drago.jpg"));
        Image img4 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images/cho.jpg"));
        Image img5 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images/luna.jpg"));
        Image img6 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images/cedric.jpg"));
       
       
       
       if(numperso != -1)
       {
           pc=ljdiag[numperso];
           
           switch(numperso)
        {
               
               
            case 0: 
            {
           for(int j=1; j<7;j++)
             { JRadioButton jr=(JRadioButton)(jPanel5.getComponent(j+2)); // decoche
             jr.setSelected(false);
             }
            // ajout des sorts
            LesArmes la = ljdiag[numperso].getArmes().getSorts();
            for(int i=0; i<la.getNbArme();i++)
            {
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort1.getText()))
                    Sort1.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort2.getText()))
                    Sort2.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort3.getText()))
                    Sort3.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort4.getText()))
                    Sort4.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort5.getText()))
                    Sort5.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort6.getText()))
                    Sort6.setSelected(true);
            }
            
            //ajout des potions                     
            la = ljdiag[numperso].getArmes().getPotions();
            DefaultListModel ls = new DefaultListModel();
            for(int i=0;i<la.getNbArme();i++)
            {     
              ls.addElement(la.getArme(i).getNom());
            }
            LPotions.setModel(ls); 
            
            // ajout de la photo
            ljdiag[numperso].getPhoto();
            img=img1;
            repaint();
                    break;}
            
            
            
            case 1: 
            {
                for(int j=1; j<7;j++)
             { JRadioButton jr=(JRadioButton)(jPanel5.getComponent(j+2));
             jr.setSelected(false);
             }
             // ajout des sorts
            LesArmes la = ljdiag[numperso].getArmes().getSorts();
            for(int i=0; i<la.getNbArme();i++)
            {
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort1.getText()))
                    Sort1.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort2.getText()))
                    Sort2.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort3.getText()))
                    Sort3.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort4.getText()))
                    Sort4.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort5.getText()))
                    Sort5.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort6.getText()))
                    Sort6.setSelected(true);                
            }
            
            //ajout des potions                     
            la = ljdiag[numperso].getArmes().getPotions();
            DefaultListModel ls = new DefaultListModel();
            for(int i=0;i<la.getNbArme();i++)
            {     
              ls.addElement(la.getArme(i).getNom());
            }
            LPotions.setModel(ls); 
            
            // ajout de la photo
            ljdiag[numperso].getPhoto();
            img=img2;
            repaint();
                    break;}
            
            
            
            case 2: 
            
            {
           for(int j=1; j<7;j++)
             { JRadioButton jr=(JRadioButton)(jPanel5.getComponent(j+2));
             jr.setSelected(false);
             }
           
             // ajout des sorts
            LesArmes la = ljdiag[numperso].getArmes().getSorts();
            for(int i=0; i<la.getNbArme();i++)
            {
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort1.getText()))
                    Sort1.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort2.getText()))
                    Sort2.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort3.getText()))
                    Sort3.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort4.getText()))
                    Sort4.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort5.getText()))
                    Sort5.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort6.getText()))
                    Sort6.setSelected(true);          
            }
            
            //ajout des potions                     
            la = ljdiag[numperso].getArmes().getPotions();
            DefaultListModel ls = new DefaultListModel();
            for(int i=0;i<la.getNbArme();i++)
            {     
              ls.addElement(la.getArme(i).getNom());
            }
            LPotions.setModel(ls); 
            
            // ajout de la photo
            ljdiag[numperso].getPhoto();
            img=img3;
            repaint();
                    break;}
            
            
            
            case 3: {
                
            for(int j=1; j<7;j++)
             { JRadioButton jr=(JRadioButton)(jPanel5.getComponent(j+2));
             jr.setSelected(false);
             }
           
             // ajout des sorts
            LesArmes la = ljdiag[numperso].getArmes().getSorts();
            for(int i=0; i<la.getNbArme();i++)
            {
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort1.getText()))
                    Sort1.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort2.getText()))
                    Sort2.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort3.getText()))
                    Sort3.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort4.getText()))
                    Sort4.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort5.getText()))
                    Sort5.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort6.getText()))
                    Sort6.setSelected(true);     
            }
            
            //ajout des potions                     
            la = ljdiag[numperso].getArmes().getPotions();
            DefaultListModel ls = new DefaultListModel();
            for(int i=0;i<la.getNbArme();i++)
            {     
              ls.addElement(la.getArme(i).getNom());
            }
            LPotions.setModel(ls); 
            
            // ajout de la photo
            ljdiag[numperso].getPhoto();
            img=img4;
            repaint();
                    break;}
            
            
            
            case 4: {
                
                for(int j=1; j<7;j++)
             { JRadioButton jr=(JRadioButton)(jPanel5.getComponent(j+2));
             jr.setSelected(false);
             }
             // ajout des sorts
            LesArmes la = ljdiag[numperso].getArmes().getSorts();
            for(int i=0; i<la.getNbArme();i++)
            {
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort1.getText()))
                    Sort1.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort2.getText()))
                    Sort2.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort3.getText()))
                    Sort3.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort4.getText()))
                    Sort4.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort5.getText()))
                    Sort5.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort6.getText()))
                    Sort6.setSelected(true); 
            }
            
            //ajout des potions                     
            la = ljdiag[numperso].getArmes().getPotions();
            DefaultListModel ls = new DefaultListModel();
            for(int i=0;i<la.getNbArme();i++)
            {     
              ls.addElement(la.getArme(i).getNom());
            }
            LPotions.setModel(ls); 
            
            // ajout de la photo
            ljdiag[numperso].getPhoto();
            img=img5;
            repaint();
                    break;}
            
            
            
            case 5: {
                
                for(int j=1; j<7;j++)
             { JRadioButton jr=(JRadioButton)(jPanel5.getComponent(j+2));
             jr.setSelected(false);
             }
                // ajout des sorts
            LesArmes la = ljdiag[numperso].getArmes().getSorts();
            for(int i=0; i<la.getNbArme();i++)
            {
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort1.getText()))
                    Sort1.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort2.getText()))
                    Sort2.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort3.getText()))
                    Sort3.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort4.getText()))
                    Sort4.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort5.getText()))
                    Sort5.setSelected(true);
                if(la.getArme(i).getNom().equalsIgnoreCase(Sort6.getText()))
                    Sort6.setSelected(true);       
            }
            
            
            //ajout des potions                     
            la = ljdiag[numperso].getArmes().getPotions();
            DefaultListModel ls = new DefaultListModel();
            for(int i=0;i<la.getNbArme();i++)
            {     
              ls.addElement(la.getArme(i).getNom());
            }
            LPotions.setModel(ls); 
            
            // ajout de la photo
            ljdiag[numperso].getPhoto();
            img=img6;
            repaint();
                    break;}
            
            
        }    
      }
    }//GEN-LAST:event_CBPersonnageActionPerformed

    private void ValiderPersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderPersoActionPerformed

       if(pc != null)
       ok = true;
       this.dispose();
    }//GEN-LAST:event_ValiderPersoActionPerformed

    private void AnnulerChoixPersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerChoixPersoActionPerformed
        this.dispose();
    }//GEN-LAST:event_AnnulerChoixPersoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnulerChoixPerso;
    private javax.swing.JComboBox<String> CBPersonnage;
    private javax.swing.JList<String> LPotions;
    private javax.swing.JPanel Panneau;
    private javax.swing.JPanel Photo;
    private javax.swing.JRadioButton Sort1;
    private javax.swing.JRadioButton Sort2;
    private javax.swing.JRadioButton Sort3;
    private javax.swing.JRadioButton Sort4;
    private javax.swing.JRadioButton Sort5;
    private javax.swing.JRadioButton Sort6;
    private javax.swing.JButton ValiderPerso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lesSorts;
    // End of variables declaration//GEN-END:variables
}
