/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ap952080
 */
public class ReglesDlg extends javax.swing.JDialog {

    /**
     * Creates new form ReglesDlg
     */
    public ReglesDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(700,700);
        this.setTitle("Les Règles");
        this.setVisible(true);
        setLocation(600,200);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Règles du Jeu");
        jPanel2.add(jLabel2);

        jPanel3.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        Edition.setEditable(false);
        Edition.setColumns(20);
        Edition.setLineWrap(true);
        Edition.setRows(5);
        Edition.setWrapStyleWord(true);
        jScrollPane2.setViewportView(Edition);
        Edition.setText("HarryPotterInfo est un jeu entre 2 joueurs\n"+
            "Au depart chaque joueur choisit le personnage-joueur qu'il va incarner "
            + "parmi 6 personnages prédéfinis de l'univers Harry Potter.\n"+
            "Chaque personnage joueur possède au départ une expérience de 200 "
            + "et un certain nombre d'armes. Il existe deux sortes d'armes : "
            + "les sorts et les potions. Chaque arme possède une certaine force.\n"+
            "Le but du jeu est d'acquérir une expérience de 500, grâce à l'acquisition d'armes.\n"+
            "Les joueurs jouent à tour de rôle.\n"+
            "A chaque tour un joueur commence par se déplacer dans un lieu qu'il choisit.\n "+
            "Chaque lieu permet d'effectuer une action spécifique :\n"+
            "   - une arène permet d'effectuer un combat contre un combattant\n"+
            "   - une salle de cours permet de faire l'apprentissage d'un sort par un maître.\n"+
            "Chaque arène possède son propre combattant, et chaque salle de cours a un maître désigné.\n"+
            "Un combat se résume à  un échange d'armes (sorts ou potions, au choix du joueur) entre le joueur et le combattant.\n"+
            "Le mécanisme diffère selon la nature des armes échangées."+
            "Lors d'un combat à base de sorts, le joueur choisit un sort parmi ceux qu'il possède, et le combattant fait de même de manière aléatoire.\n"+
            " Celui qui propose le sort de plus grande force remporte le combat.\n"+
            "Lors d'un combat à base de potions, le joueur choisit un certain nombre de potions parmi celles qu'il possède, "+
            "et le combattant choisit quant à lui une seule potion de manière aléatoire.\n"+
            " Celui qui a la force (ou la somme des forces) de plus grande valeur remporte le combat.\n"+
            "Si le joueur gagne le combat, il acquiert l'arme (sort ou potion) proposée par son adversaire, et augmente son expérience de la force de l'arme gagnée.\n"+
            "S'il perd, il diminue son expérience de la force de l'arme (ou des armes) qu'il a utilisée(s) dans le combat,\n"+
            "mais ne perd pas son (ou ses) arme(s).\n"+
            "Dans une salle de cours, le joueur choisit le sort qu'il veut apprendre parmi ceux que possède le maître de la salle.\n"+
            "L'apprentissage aboutit si l'expérience du joueur augmentée d'un nombre entier aléatoire\n"+
            " est supérieure ou égale à l'expérience du maître.\n"+
            "Si le joueur apprend le sort, il le rajoute à sa liste de sorts, et augmente son expérience de la force du sort appris.\n"+
            "Si le joueur ne réussit pas à apprendre le sort voulu, il ne perd rien.\n"+
            "Celui qui gagne est celui qui a atteint le premier au moins 500 en expérience\n"+
            " ou bien qui n'a plus d'adversaire valide (plus de sort ni de potion ni d'expérience)\n"+
            "Bonne chance");

        jPanel4.add(jScrollPane2);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.GridLayout(1, 3));
        jPanel5.add(jLabel3);
        jPanel5.add(jLabel4);

        Fermer.setText("Fermer");
        Fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FermerActionPerformed(evt);
            }
        });
        jPanel5.add(Fermer);

        jPanel3.add(jPanel5, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FermerActionPerformed
        this.dispose();
    }//GEN-LAST:event_FermerActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Edition;
    private javax.swing.JButton Fermer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
